version: '3.8'
services:
  db:
    image: supabase/postgres:15.1.0.73
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  studio:
    image: supabase/studio:latest
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      STUDIO_PG_META_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      ANON_KEY: ${ANON_KEY}
      SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}

volumes:
  db_data:
